// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIgk-TeMOo4jQmT_Z-mAFOpnrdquq6Nmg',
    appId: '1:669707327272:web:fb70cf0dc2c3a4a7e3221d',
    messagingSenderId: '669707327272',
    projectId: 'praneethb7-mynotes',
    authDomain: 'praneethb7-mynotes.firebaseapp.com',
    storageBucket: 'praneethb7-mynotes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnth2ov-fAEICzAjGx-XVJjbAv3BOUgmE',
    appId: '1:669707327272:android:146018825eea21b2e3221d',
    messagingSenderId: '669707327272',
    projectId: 'praneethb7-mynotes',
    storageBucket: 'praneethb7-mynotes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3lucgiLVtRHYaMGr10zJHla1zzt19qL0',
    appId: '1:669707327272:ios:1bf4a6b7a11b334ee3221d',
    messagingSenderId: '669707327272',
    projectId: 'praneethb7-mynotes',
    storageBucket: 'praneethb7-mynotes.firebasestorage.app',
    iosBundleId: 'com.example.mynotes.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3lucgiLVtRHYaMGr10zJHla1zzt19qL0',
    appId: '1:669707327272:ios:9abe266364cd5689e3221d',
    messagingSenderId: '669707327272',
    projectId: 'praneethb7-mynotes',
    storageBucket: 'praneethb7-mynotes.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIgk-TeMOo4jQmT_Z-mAFOpnrdquq6Nmg',
    appId: '1:669707327272:web:66a95a21e2eb3581e3221d',
    messagingSenderId: '669707327272',
    projectId: 'praneethb7-mynotes',
    authDomain: 'praneethb7-mynotes.firebaseapp.com',
    storageBucket: 'praneethb7-mynotes.firebasestorage.app',
  );
}
